# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/team_draft_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# Faz o Hibernate criar/atualizar as tabelas automaticamente baseado nas nossas classes Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code as queries SQL que o Spring está executando por baixo dos panos (Excelente para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true